services:
  mongo:
    image: mongo
    env_file:
      - .env
    restart: no
    expose:
      - "27017"
    networks:
      - support-service
    volumes:
      - support-service-mongodb-data:/data/db

  mongo-express:
    image: mongo-express
    env_file:
      - .env
    restart: no
    ports:
      - "8081:8081"
    networks:
      - support-service

  redis:
    image: redis:alpine
    container_name: support-service-redis
    restart: no
    expose:
      - "6379"
    volumes:
      - support-service-redis-data:/data
    networks:
      - support-service

  redis-commander:
    container_name: support-service-redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8086:8081"
    depends_on:
      - "redis"
    networks:
      - support-service

  support-service:
    build:
      context: .
    container_name: support-service
    volumes:
      - ./src:/code
    env_file:
      - .env
    restart: no
    ports:
      - "8000:80"
    expose:
      - "80"
    networks:
      - support-service
      - gateway
    depends_on:
      - mongo
      - redis


volumes:
  support-service-mongodb-data:
  support-service-redis-data:

networks:
  support-service:
  gateway:
    external: true
