services:
  mongo:
    image: mongo
    container_name: mongo
    env_file:
      - .env
    restart: no
    ports:
      - "27017:27017"
    networks:
      - main
    volumes:
      - mongodb-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    env_file:
      - .env
    restart: no
    ports:
      - "8081:8081"
    networks:
      - main
    depends_on:
      - mongo
  redis:
    image: redis:alpine
    container_name: support-service-redis
    restart: no
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - main
  support-service:
    build:
      context: .
    container_name: support-service
    volumes:
      - ./src:/code
    env_file:
      - .env
    restart: no
    ports:
      - "8000:8000"
    networks:
      - main
    depends_on:
      - mongo

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - main

volumes:
  mongodb-data:
  redis-data:

networks:
  main:
    driver: bridge
